export enum Filters {
  PLENO_FILTER = 'bet.plenoNumbers.number',
  SEMIPLENO_FILTER = 'bet.semiPlenoNumbers.number',
  CALLE_FILTER = 'bet.calleNumbers.number',
  CUADRO_FILTER = 'bet.cuadroNumbers.number',
  LINEA_FILTER = 'bet.lineaNumbers.number',
  EVEN_ODD = 'bet.even_odd.type',
  COLOR = 'bet.color.type',
  COLUMNS = 'bet.columns.type',
  DOZENS = 'bet.dozens.type',
  CHANCE_SIMPLE = 'bet.chanceSimple.type',
  CUBRE = 'bet.cubre.type',
}

export enum FiltersAmerican {
  PLENO_FILTER = 'bet.plenoNumbers.number',
  SEMIPLENO_FILTER = 'bet.semiPlenoNumbers.number',
  CALLE_FILTER = 'bet.calleNumbers.number',
  CUADRO_FILTER = 'bet.cuadroNumbers.number',
  LINEA_FILTER = 'bet.lineaNumbers.number',
  EVEN_ODD = 'bet.even_odd.type',
  COLOR = 'bet.color.type',
  COLUMNS = 'bet.columns.type',
  DOZENS = 'bet.dozens.type',
  CHANCE_SIMPLE = 'bet.chanceSimple.type',
  CUBRE = 'bet.cubre.type',
  SPECIAL_CALLE = 'bet.specialCalle.type',
}

export enum BetEnums {
  PLENO_AMOUNT = 'plenoAmount',
  SEMI_PLENO_AMOUNT = 'semiPlenoAmount',
  CALLE_AMOUNT = 'calleAmount',
  CUADRO_AMOUNT = 'cuadroAmount',
  LINEA_AMOUNT = 'lineaAmount',
  CUBRE_FIRST = 'cubre0_1_2',
  CUBRE_SECOND = 'cubre0_2_3',
  ODD_AMOUNT = 'oddAmount',
  EVEN_AMOUNT = 'evenAmount',
  FIRST_COLUMN_AMOUNT = 'firstColumnAmount',
  SECOND_COLUMN_AMOUNT = 'secondColumnAmount',
  THIRD_COLUMN_AMOUNT = 'thirdColumnAmount',
  FIRST_DOZEN_AMOUNT = 'firstDozenAmount',
  SECOND_DOZEN_AMOUNT = 'secondDozenAmount',
  THIRD_DOZEN_AMOUNT = 'thirdDozenAmount',
  CHANCE_SIMPLE_1_18 = 'chanceSimple1_18',
  CHANCE_SIMPLE_19_36 = 'chanceSimple19_36',
  RED_AMOUNT = 'redAmount',
  BLACK_AMOUNT = 'blackAmount',
}

export enum BetEnumsAmericans {
  PLENO_AMOUNT = 'plenoAmount',
  SEMI_PLENO_AMOUNT = 'semiPlenoAmount',
  CALLE_AMOUNT = 'calleAmount',
  CUADRO_AMOUNT = 'cuadroAmount',
  LINEA_AMOUNT = 'lineaAmount',
  CUBRE_0_1_2 = 'cubre0_1_2',
  CUBRE_0_37_2 = 'cubre0_37_2',
  CUBRE_37_2_3 = 'cubre37_2_3',
  SPECIAL_CALLE = 'specialCalle',
  ODD_AMOUNT = 'oddAmount',
  EVEN_AMOUNT = 'evenAmount',
  FIRST_COLUMN_AMOUNT = 'firstColumnAmount',
  SECOND_COLUMN_AMOUNT = 'secondColumnAmount',
  THIRD_COLUMN_AMOUNT = 'thirdColumnAmount',
  FIRST_DOZEN_AMOUNT = 'firstDozenAmount',
  SECOND_DOZEN_AMOUNT = 'secondDozenAmount',
  THIRD_DOZEN_AMOUNT = 'thirdDozenAmount',
  CHANCE_SIMPLE_1_18 = 'chanceSimple1_18',
  CHANCE_SIMPLE_19_36 = 'chanceSimple19_36',
  RED_AMOUNT = 'redAmount',
  BLACK_AMOUNT = 'blackAmount',
}

export enum Bets {
  PLENO = 'plenoNumbers',
  SEMI_PLENO = 'semiPlenoNumbers',
  CALLE = 'calleNumbers',
  CUADRO = 'cuadroNumbers',
  LINEA = 'lineaNumbers',
  EVEN_ODD = 'even_odd',
  COLOR = 'color',
  COLUMN = 'columns',
  DOZEN = 'dozens',
  CHANCE_SIMPLE = 'chanceSimple',
  CUBRE = 'cubre',
}

export enum BetsAmerican {
  PLENO = 'plenoNumbers',
  SEMI_PLENO = 'semiPlenoNumbers',
  CALLE = 'calleNumbers',
  CUADRO = 'cuadroNumbers',
  LINEA = 'lineaNumbers',
  EVEN_ODD = 'even_odd',
  COLOR = 'color',
  COLUMN = 'columns',
  DOZEN = 'dozens',
  CHANCE_SIMPLE = 'chanceSimple',
  CUBRE = 'cubre',
  SPECIAL_CALLE = 'specialCalle',
}
